import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-8">
          <h1 className="mb-16 mx-0 px-0 text-4xl font-bold">
            Awesome Amazon Products
          </h1>
          {children}
        </div>
      </body>
    </html>
  );
}
